### ISSUE TITLE
`.pyc` files should not be version controlled

### ISSUE THREAD

**Issue by jxcl** [KeynesYouDigIt/Vasco_de_data#1]
`.pyc` files are compiled python files that are not part of the source code. ~~I recommend adding the line `*.pyc` to your `.gitignore` in this and future projects to avoid accidentally committing them to the repo.~~ (I see that you have already done that, I still suggest going through and removing them from the project)

**Comment by KeynesYouDigIt** [comment]
Yeah this has been an ongoing issue, gotta dig a bit deeper to figure out how to get rid of them.
