### ISSUE TITLE
Python Style

### ISSUE THREAD

**Issue by jxcl** [KeynesYouDigIt/Vasco_de_data#2]
This is a great project! I wish my first projects where anywhere near as cool. I'm going to leave a few comments about conventional Python style here. I hope this helps you out in learning python!

[1) Multiline Strings:](https://github.com/KeynesYouDigIt/Vasco_de_data/blob/master/Vasco/views.py#L55)

You've got a really long line here, with newline literals in it. Python allows you to break long strings in cool ways. You clearly know about multiline strings that use three quotes in a row, but there's another option that looks like this: 

```
final=('Please select. don\'t be scared if the list is long!'
       'for now you can hit ctrl + f to search on most browsers. \n'
       'by the end of this year, there will be a smoother selection'
       'experience that will help you find your data.')
```

Also, the cool thing about having both `"` and `'` as string operators in Python means that you can use one when the string contains the other, so that you don't have to escape quotes as often. The string `"don't"`, for example, will work without the quote escaped.

2) Line length in general

It's a good idea to keep your lines short, about 80-100 characters as the limit. It makes it much easier for other people to read your code. I suggest breaking up your dictionaries and other long lines into multiple lines. As an example:

```
data_return = db.engine.execute(text(query),
                                {
                                    'display_name': tuple(indic_form.indicators.data),
                                    'name': tuple(order_c),
                                    'years': tuple(order_y)
                                }).fetchall()
```

That's much easier to read, in my opinion, although I might go further and pull the dictionary out into a variable to make the function call shorter.

There are some other small issues I see. If you run [Pylint](https://www.pylint.org/) on your code, it will help you find and fix many of them.

Happy coding!

**Comment by KeynesYouDigIt** [comment]
You are the man Alex! I will jump on these as soon as I can.

**Comment by KeynesYouDigIt** [comment]
Most of this is taken care of, will close. Please reopen if you see more!
